// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: orchestrator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowRunId     string                 `protobuf:"bytes,1,opt,name=flow_run_id,json=flowRunId,proto3" json:"flow_run_id,omitempty"`
	WorkflowDsl   string                 `protobuf:"bytes,2,opt,name=workflow_dsl,json=workflowDsl,proto3" json:"workflow_dsl,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,5,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFlowRequest) Reset() {
	*x = StartFlowRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFlowRequest) ProtoMessage() {}

func (x *StartFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFlowRequest.ProtoReflect.Descriptor instead.
func (*StartFlowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *StartFlowRequest) GetFlowRunId() string {
	if x != nil {
		return x.FlowRunId
	}
	return ""
}

func (x *StartFlowRequest) GetWorkflowDsl() string {
	if x != nil {
		return x.WorkflowDsl
	}
	return ""
}

func (x *StartFlowRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *StartFlowRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartFlowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type StartFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFlowResponse) Reset() {
	*x = StartFlowResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFlowResponse) ProtoMessage() {}

func (x *StartFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFlowResponse.ProtoReflect.Descriptor instead.
func (*StartFlowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *StartFlowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartFlowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowRunId     string                 `protobuf:"bytes,1,opt,name=flow_run_id,json=flowRunId,proto3" json:"flow_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFlowRequest) Reset() {
	*x = CancelFlowRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFlowRequest) ProtoMessage() {}

func (x *CancelFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFlowRequest.ProtoReflect.Descriptor instead.
func (*CancelFlowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *CancelFlowRequest) GetFlowRunId() string {
	if x != nil {
		return x.FlowRunId
	}
	return ""
}

type CancelFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFlowResponse) Reset() {
	*x = CancelFlowResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFlowResponse) ProtoMessage() {}

func (x *CancelFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFlowResponse.ProtoReflect.Descriptor instead.
func (*CancelFlowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CancelFlowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelFlowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApproveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRunId     string                 `protobuf:"bytes,1,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveNodeRequest) Reset() {
	*x = ApproveNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveNodeRequest) ProtoMessage() {}

func (x *ApproveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveNodeRequest.ProtoReflect.Descriptor instead.
func (*ApproveNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveNodeRequest) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

type RejectNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRunId     string                 `protobuf:"bytes,1,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	Feedback      string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectNodeRequest) Reset() {
	*x = RejectNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectNodeRequest) ProtoMessage() {}

func (x *RejectNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectNodeRequest.ProtoReflect.Descriptor instead.
func (*RejectNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *RejectNodeRequest) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

func (x *RejectNodeRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type EditNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRunId     string                 `protobuf:"bytes,1,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	EditedContent string                 `protobuf:"bytes,2,opt,name=edited_content,json=editedContent,proto3" json:"edited_content,omitempty"`
	ChangeSummary string                 `protobuf:"bytes,3,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditNodeRequest) Reset() {
	*x = EditNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditNodeRequest) ProtoMessage() {}

func (x *EditNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditNodeRequest.ProtoReflect.Descriptor instead.
func (*EditNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *EditNodeRequest) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

func (x *EditNodeRequest) GetEditedContent() string {
	if x != nil {
		return x.EditedContent
	}
	return ""
}

func (x *EditNodeRequest) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

type SubmitHumanInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRunId     string                 `protobuf:"bytes,1,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitHumanInputRequest) Reset() {
	*x = SubmitHumanInputRequest{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHumanInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHumanInputRequest) ProtoMessage() {}

func (x *SubmitHumanInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHumanInputRequest.ProtoReflect.Descriptor instead.
func (*SubmitHumanInputRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitHumanInputRequest) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

func (x *SubmitHumanInputRequest) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type RetryNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRunId     string                 `protobuf:"bytes,1,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryNodeRequest) Reset() {
	*x = RetryNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryNodeRequest) ProtoMessage() {}

func (x *RetryNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryNodeRequest.ProtoReflect.Descriptor instead.
func (*RetryNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *RetryNodeRequest) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

type NodeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeActionResponse) Reset() {
	*x = NodeActionResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeActionResponse) ProtoMessage() {}

func (x *NodeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeActionResponse.ProtoReflect.Descriptor instead.
func (*NodeActionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *NodeActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleId         string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AgentType      string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	ProviderId     *string                `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	ProviderConfig map[string]string      `protobuf:"bytes,4,rep,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModelName      *string                `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3,oneof" json:"model_name,omitempty"`
	SystemPrompt   string                 `protobuf:"bytes,6,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	TestPrompt     string                 `protobuf:"bytes,7,opt,name=test_prompt,json=testPrompt,proto3" json:"test_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestAgentRequest) Reset() {
	*x = TestAgentRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAgentRequest) ProtoMessage() {}

func (x *TestAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAgentRequest.ProtoReflect.Descriptor instead.
func (*TestAgentRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *TestAgentRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *TestAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *TestAgentRequest) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *TestAgentRequest) GetProviderConfig() map[string]string {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *TestAgentRequest) GetModelName() string {
	if x != nil && x.ModelName != nil {
		return *x.ModelName
	}
	return ""
}

func (x *TestAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *TestAgentRequest) GetTestPrompt() string {
	if x != nil {
		return x.TestPrompt
	}
	return ""
}

type TestAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        *string                `protobuf:"bytes,2,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Logs          []string               `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAgentResponse) Reset() {
	*x = TestAgentResponse{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAgentResponse) ProtoMessage() {}

func (x *TestAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAgentResponse.ProtoReflect.Descriptor instead.
func (*TestAgentResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *TestAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestAgentResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *TestAgentResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *TestAgentResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ReloadAgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadAgentConfigRequest) Reset() {
	*x = ReloadAgentConfigRequest{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadAgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAgentConfigRequest) ProtoMessage() {}

func (x *ReloadAgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAgentConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadAgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

type ReloadAgentConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	ProvidersLoaded int32                  `protobuf:"varint,3,opt,name=providers_loaded,json=providersLoaded,proto3" json:"providers_loaded,omitempty"`
	RolesMapped     int32                  `protobuf:"varint,4,opt,name=roles_mapped,json=rolesMapped,proto3" json:"roles_mapped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReloadAgentConfigResponse) Reset() {
	*x = ReloadAgentConfigResponse{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAgentConfigResponse) ProtoMessage() {}

func (x *ReloadAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *ReloadAgentConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadAgentConfigResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ReloadAgentConfigResponse) GetProvidersLoaded() int32 {
	if x != nil {
		return x.ProvidersLoaded
	}
	return 0
}

func (x *ReloadAgentConfigResponse) GetRolesMapped() int32 {
	if x != nil {
		return x.RolesMapped
	}
	return 0
}

type EventStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowRunId     string                 `protobuf:"bytes,1,opt,name=flow_run_id,json=flowRunId,proto3" json:"flow_run_id,omitempty"` // 可选，为空则接收所有事件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *EventStreamRequest) GetFlowRunId() string {
	if x != nil {
		return x.FlowRunId
	}
	return ""
}

type ServerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // node.queued / node.started / node.completed / node.waiting_human / node.failed / node.rejected / flow.started / flow.completed / flow.failed / flow.cancelled
	FlowRunId     string                 `protobuf:"bytes,2,opt,name=flow_run_id,json=flowRunId,proto3" json:"flow_run_id,omitempty"`
	NodeRunId     string                 `protobuf:"bytes,3,opt,name=node_run_id,json=nodeRunId,proto3" json:"node_run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON 序列化的事件数据
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *ServerEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ServerEvent) GetFlowRunId() string {
	if x != nil {
		return x.FlowRunId
	}
	return ""
}

func (x *ServerEvent) GetNodeRunId() string {
	if x != nil {
		return x.NodeRunId
	}
	return ""
}

func (x *ServerEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServerEvent) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *ServerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\forchestrator\"\x9a\x02\n" +
	"\x10StartFlowRequest\x12\x1e\n" +
	"\vflow_run_id\x18\x01 \x01(\tR\tflowRunId\x12!\n" +
	"\fworkflow_dsl\x18\x02 \x01(\tR\vworkflowDsl\x12K\n" +
	"\tvariables\x18\x03 \x03(\v2-.orchestrator.StartFlowRequest.VariablesEntryR\tvariables\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x05 \x01(\tR\n" +
	"workflowId\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x11StartFlowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x11CancelFlowRequest\x12\x1e\n" +
	"\vflow_run_id\x18\x01 \x01(\tR\tflowRunId\"D\n" +
	"\x12CancelFlowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x12ApproveNodeRequest\x12\x1e\n" +
	"\vnode_run_id\x18\x01 \x01(\tR\tnodeRunId\"O\n" +
	"\x11RejectNodeRequest\x12\x1e\n" +
	"\vnode_run_id\x18\x01 \x01(\tR\tnodeRunId\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\"\x7f\n" +
	"\x0fEditNodeRequest\x12\x1e\n" +
	"\vnode_run_id\x18\x01 \x01(\tR\tnodeRunId\x12%\n" +
	"\x0eedited_content\x18\x02 \x01(\tR\reditedContent\x12%\n" +
	"\x0echange_summary\x18\x03 \x01(\tR\rchangeSummary\"V\n" +
	"\x17SubmitHumanInputRequest\x12\x1e\n" +
	"\vnode_run_id\x18\x01 \x01(\tR\tnodeRunId\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"2\n" +
	"\x10RetryNodeRequest\x12\x1e\n" +
	"\vnode_run_id\x18\x01 \x01(\tR\tnodeRunId\"D\n" +
	"\x12NodeActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x99\x03\n" +
	"\x10TestAgentRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12$\n" +
	"\vprovider_id\x18\x03 \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x12[\n" +
	"\x0fprovider_config\x18\x04 \x03(\v22.orchestrator.TestAgentRequest.ProviderConfigEntryR\x0eproviderConfig\x12\"\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tH\x01R\tmodelName\x88\x01\x01\x12#\n" +
	"\rsystem_prompt\x18\x06 \x01(\tR\fsystemPrompt\x12\x1f\n" +
	"\vtest_prompt\x18\a \x01(\tR\n" +
	"testPrompt\x1aA\n" +
	"\x13ProviderConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_provider_idB\r\n" +
	"\v_model_name\"\x8e\x01\n" +
	"\x11TestAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06result\x18\x02 \x01(\tH\x00R\x06result\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x12\n" +
	"\x04logs\x18\x04 \x03(\tR\x04logsB\t\n" +
	"\a_resultB\b\n" +
	"\x06_error\"\x1a\n" +
	"\x18ReloadAgentConfigRequest\"\xa8\x01\n" +
	"\x19ReloadAgentConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12)\n" +
	"\x10providers_loaded\x18\x03 \x01(\x05R\x0fprovidersLoaded\x12!\n" +
	"\froles_mapped\x18\x04 \x01(\x05R\vrolesMappedB\b\n" +
	"\x06_error\"4\n" +
	"\x12EventStreamRequest\x12\x1e\n" +
	"\vflow_run_id\x18\x01 \x01(\tR\tflowRunId\"\xc0\x01\n" +
	"\vServerEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1e\n" +
	"\vflow_run_id\x18\x02 \x01(\tR\tflowRunId\x12\x1e\n" +
	"\vnode_run_id\x18\x03 \x01(\tR\tnodeRunId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp2\xd3\x06\n" +
	"\x13OrchestratorService\x12L\n" +
	"\tStartFlow\x12\x1e.orchestrator.StartFlowRequest\x1a\x1f.orchestrator.StartFlowResponse\x12O\n" +
	"\n" +
	"CancelFlow\x12\x1f.orchestrator.CancelFlowRequest\x1a .orchestrator.CancelFlowResponse\x12Q\n" +
	"\vApproveNode\x12 .orchestrator.ApproveNodeRequest\x1a .orchestrator.NodeActionResponse\x12O\n" +
	"\n" +
	"RejectNode\x12\x1f.orchestrator.RejectNodeRequest\x1a .orchestrator.NodeActionResponse\x12K\n" +
	"\bEditNode\x12\x1d.orchestrator.EditNodeRequest\x1a .orchestrator.NodeActionResponse\x12[\n" +
	"\x10SubmitHumanInput\x12%.orchestrator.SubmitHumanInputRequest\x1a .orchestrator.NodeActionResponse\x12M\n" +
	"\tRetryNode\x12\x1e.orchestrator.RetryNodeRequest\x1a .orchestrator.NodeActionResponse\x12L\n" +
	"\tTestAgent\x12\x1e.orchestrator.TestAgentRequest\x1a\x1f.orchestrator.TestAgentResponse\x12d\n" +
	"\x11ReloadAgentConfig\x12&.orchestrator.ReloadAgentConfigRequest\x1a'.orchestrator.ReloadAgentConfigResponse\x12L\n" +
	"\vEventStream\x12 .orchestrator.EventStreamRequest\x1a\x19.orchestrator.ServerEvent0\x01B;Z9github.com/sunshow/workgear/orchestrator/internal/grpc/pbb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_orchestrator_proto_goTypes = []any{
	(*StartFlowRequest)(nil),          // 0: orchestrator.StartFlowRequest
	(*StartFlowResponse)(nil),         // 1: orchestrator.StartFlowResponse
	(*CancelFlowRequest)(nil),         // 2: orchestrator.CancelFlowRequest
	(*CancelFlowResponse)(nil),        // 3: orchestrator.CancelFlowResponse
	(*ApproveNodeRequest)(nil),        // 4: orchestrator.ApproveNodeRequest
	(*RejectNodeRequest)(nil),         // 5: orchestrator.RejectNodeRequest
	(*EditNodeRequest)(nil),           // 6: orchestrator.EditNodeRequest
	(*SubmitHumanInputRequest)(nil),   // 7: orchestrator.SubmitHumanInputRequest
	(*RetryNodeRequest)(nil),          // 8: orchestrator.RetryNodeRequest
	(*NodeActionResponse)(nil),        // 9: orchestrator.NodeActionResponse
	(*TestAgentRequest)(nil),          // 10: orchestrator.TestAgentRequest
	(*TestAgentResponse)(nil),         // 11: orchestrator.TestAgentResponse
	(*ReloadAgentConfigRequest)(nil),  // 12: orchestrator.ReloadAgentConfigRequest
	(*ReloadAgentConfigResponse)(nil), // 13: orchestrator.ReloadAgentConfigResponse
	(*EventStreamRequest)(nil),        // 14: orchestrator.EventStreamRequest
	(*ServerEvent)(nil),               // 15: orchestrator.ServerEvent
	nil,                               // 16: orchestrator.StartFlowRequest.VariablesEntry
	nil,                               // 17: orchestrator.TestAgentRequest.ProviderConfigEntry
}
var file_orchestrator_proto_depIdxs = []int32{
	16, // 0: orchestrator.StartFlowRequest.variables:type_name -> orchestrator.StartFlowRequest.VariablesEntry
	17, // 1: orchestrator.TestAgentRequest.provider_config:type_name -> orchestrator.TestAgentRequest.ProviderConfigEntry
	0,  // 2: orchestrator.OrchestratorService.StartFlow:input_type -> orchestrator.StartFlowRequest
	2,  // 3: orchestrator.OrchestratorService.CancelFlow:input_type -> orchestrator.CancelFlowRequest
	4,  // 4: orchestrator.OrchestratorService.ApproveNode:input_type -> orchestrator.ApproveNodeRequest
	5,  // 5: orchestrator.OrchestratorService.RejectNode:input_type -> orchestrator.RejectNodeRequest
	6,  // 6: orchestrator.OrchestratorService.EditNode:input_type -> orchestrator.EditNodeRequest
	7,  // 7: orchestrator.OrchestratorService.SubmitHumanInput:input_type -> orchestrator.SubmitHumanInputRequest
	8,  // 8: orchestrator.OrchestratorService.RetryNode:input_type -> orchestrator.RetryNodeRequest
	10, // 9: orchestrator.OrchestratorService.TestAgent:input_type -> orchestrator.TestAgentRequest
	12, // 10: orchestrator.OrchestratorService.ReloadAgentConfig:input_type -> orchestrator.ReloadAgentConfigRequest
	14, // 11: orchestrator.OrchestratorService.EventStream:input_type -> orchestrator.EventStreamRequest
	1,  // 12: orchestrator.OrchestratorService.StartFlow:output_type -> orchestrator.StartFlowResponse
	3,  // 13: orchestrator.OrchestratorService.CancelFlow:output_type -> orchestrator.CancelFlowResponse
	9,  // 14: orchestrator.OrchestratorService.ApproveNode:output_type -> orchestrator.NodeActionResponse
	9,  // 15: orchestrator.OrchestratorService.RejectNode:output_type -> orchestrator.NodeActionResponse
	9,  // 16: orchestrator.OrchestratorService.EditNode:output_type -> orchestrator.NodeActionResponse
	9,  // 17: orchestrator.OrchestratorService.SubmitHumanInput:output_type -> orchestrator.NodeActionResponse
	9,  // 18: orchestrator.OrchestratorService.RetryNode:output_type -> orchestrator.NodeActionResponse
	11, // 19: orchestrator.OrchestratorService.TestAgent:output_type -> orchestrator.TestAgentResponse
	13, // 20: orchestrator.OrchestratorService.ReloadAgentConfig:output_type -> orchestrator.ReloadAgentConfigResponse
	15, // 21: orchestrator.OrchestratorService.EventStream:output_type -> orchestrator.ServerEvent
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_orchestrator_proto_msgTypes[10].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[11].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
