// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: orchestrator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_StartFlow_FullMethodName         = "/orchestrator.OrchestratorService/StartFlow"
	OrchestratorService_CancelFlow_FullMethodName        = "/orchestrator.OrchestratorService/CancelFlow"
	OrchestratorService_ApproveNode_FullMethodName       = "/orchestrator.OrchestratorService/ApproveNode"
	OrchestratorService_RejectNode_FullMethodName        = "/orchestrator.OrchestratorService/RejectNode"
	OrchestratorService_EditNode_FullMethodName          = "/orchestrator.OrchestratorService/EditNode"
	OrchestratorService_SubmitHumanInput_FullMethodName  = "/orchestrator.OrchestratorService/SubmitHumanInput"
	OrchestratorService_RetryNode_FullMethodName         = "/orchestrator.OrchestratorService/RetryNode"
	OrchestratorService_RerunNode_FullMethodName         = "/orchestrator.OrchestratorService/RerunNode"
	OrchestratorService_SkipNode_FullMethodName          = "/orchestrator.OrchestratorService/SkipNode"
	OrchestratorService_TestAgent_FullMethodName         = "/orchestrator.OrchestratorService/TestAgent"
	OrchestratorService_ReloadAgentConfig_FullMethodName = "/orchestrator.OrchestratorService/ReloadAgentConfig"
	OrchestratorService_EventStream_FullMethodName       = "/orchestrator.OrchestratorService/EventStream"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	// 流程管理
	StartFlow(ctx context.Context, in *StartFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error)
	CancelFlow(ctx context.Context, in *CancelFlowRequest, opts ...grpc.CallOption) (*CancelFlowResponse, error)
	// 人工操作
	ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	RejectNode(ctx context.Context, in *RejectNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	EditNode(ctx context.Context, in *EditNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	SubmitHumanInput(ctx context.Context, in *SubmitHumanInputRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	RetryNode(ctx context.Context, in *RetryNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	RerunNode(ctx context.Context, in *RetryNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error)
	// Agent 测试
	TestAgent(ctx context.Context, in *TestAgentRequest, opts ...grpc.CallOption) (*TestAgentResponse, error)
	// Agent 配置热重载
	ReloadAgentConfig(ctx context.Context, in *ReloadAgentConfigRequest, opts ...grpc.CallOption) (*ReloadAgentConfigResponse, error)
	// 事件流（服务端流式推送）
	EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerEvent], error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) StartFlow(ctx context.Context, in *StartFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_StartFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CancelFlow(ctx context.Context, in *CancelFlowRequest, opts ...grpc.CallOption) (*CancelFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelFlowResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CancelFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ApproveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RejectNode(ctx context.Context, in *RejectNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RejectNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) EditNode(ctx context.Context, in *EditNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_EditNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SubmitHumanInput(ctx context.Context, in *SubmitHumanInputRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitHumanInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RetryNode(ctx context.Context, in *RetryNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RetryNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RerunNode(ctx context.Context, in *RetryNodeRequest, opts ...grpc.CallOption) (*NodeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeActionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RerunNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) TestAgent(ctx context.Context, in *TestAgentRequest, opts ...grpc.CallOption) (*TestAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestAgentResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_TestAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ReloadAgentConfig(ctx context.Context, in *ReloadAgentConfigRequest, opts ...grpc.CallOption) (*ReloadAgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadAgentConfigResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ReloadAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], OrchestratorService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamRequest, ServerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_EventStreamClient = grpc.ServerStreamingClient[ServerEvent]

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
type OrchestratorServiceServer interface {
	// 流程管理
	StartFlow(context.Context, *StartFlowRequest) (*StartFlowResponse, error)
	CancelFlow(context.Context, *CancelFlowRequest) (*CancelFlowResponse, error)
	// 人工操作
	ApproveNode(context.Context, *ApproveNodeRequest) (*NodeActionResponse, error)
	RejectNode(context.Context, *RejectNodeRequest) (*NodeActionResponse, error)
	EditNode(context.Context, *EditNodeRequest) (*NodeActionResponse, error)
	SubmitHumanInput(context.Context, *SubmitHumanInputRequest) (*NodeActionResponse, error)
	RetryNode(context.Context, *RetryNodeRequest) (*NodeActionResponse, error)
	RerunNode(context.Context, *RetryNodeRequest) (*NodeActionResponse, error)
	SkipNode(context.Context, *SubmitHumanInputRequest) (*NodeActionResponse, error)
	// Agent 测试
	TestAgent(context.Context, *TestAgentRequest) (*TestAgentResponse, error)
	// Agent 配置热重载
	ReloadAgentConfig(context.Context, *ReloadAgentConfigRequest) (*ReloadAgentConfigResponse, error)
	// 事件流（服务端流式推送）
	EventStream(*EventStreamRequest, grpc.ServerStreamingServer[ServerEvent]) error
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) StartFlow(context.Context, *StartFlowRequest) (*StartFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartFlow not implemented")
}
func (UnimplementedOrchestratorServiceServer) CancelFlow(context.Context, *CancelFlowRequest) (*CancelFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelFlow not implemented")
}
func (UnimplementedOrchestratorServiceServer) ApproveNode(context.Context, *ApproveNodeRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) RejectNode(context.Context, *RejectNodeRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) EditNode(context.Context, *EditNodeRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) SubmitHumanInput(context.Context, *SubmitHumanInputRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHumanInput not implemented")
}
func (UnimplementedOrchestratorServiceServer) RetryNode(context.Context, *RetryNodeRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) RerunNode(context.Context, *RetryNodeRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RerunNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) SkipNode(context.Context, *SubmitHumanInputRequest) (*NodeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) TestAgent(context.Context, *TestAgentRequest) (*TestAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestAgent not implemented")
}
func (UnimplementedOrchestratorServiceServer) ReloadAgentConfig(context.Context, *ReloadAgentConfigRequest) (*ReloadAgentConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadAgentConfig not implemented")
}
func (UnimplementedOrchestratorServiceServer) EventStream(*EventStreamRequest, grpc.ServerStreamingServer[ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_StartFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StartFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_StartFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StartFlow(ctx, req.(*StartFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CancelFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CancelFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CancelFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CancelFlow(ctx, req.(*CancelFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ApproveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ApproveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ApproveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ApproveNode(ctx, req.(*ApproveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RejectNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RejectNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RejectNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RejectNode(ctx, req.(*RejectNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_EditNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).EditNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_EditNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).EditNode(ctx, req.(*EditNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SubmitHumanInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHumanInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitHumanInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitHumanInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitHumanInput(ctx, req.(*SubmitHumanInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RetryNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RetryNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RetryNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RetryNode(ctx, req.(*RetryNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RerunNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RerunNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RerunNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RerunNode(ctx, req.(*RetryNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SkipNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHumanInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SkipNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SkipNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SkipNode(ctx, req.(*SubmitHumanInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_TestAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).TestAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_TestAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).TestAgent(ctx, req.(*TestAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ReloadAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReloadAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReloadAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReloadAgentConfig(ctx, req.(*ReloadAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).EventStream(m, &grpc.GenericServerStream[EventStreamRequest, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_EventStreamServer = grpc.ServerStreamingServer[ServerEvent]

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFlow",
			Handler:    _OrchestratorService_StartFlow_Handler,
		},
		{
			MethodName: "CancelFlow",
			Handler:    _OrchestratorService_CancelFlow_Handler,
		},
		{
			MethodName: "ApproveNode",
			Handler:    _OrchestratorService_ApproveNode_Handler,
		},
		{
			MethodName: "RejectNode",
			Handler:    _OrchestratorService_RejectNode_Handler,
		},
		{
			MethodName: "EditNode",
			Handler:    _OrchestratorService_EditNode_Handler,
		},
		{
			MethodName: "SubmitHumanInput",
			Handler:    _OrchestratorService_SubmitHumanInput_Handler,
		},
		{
			MethodName: "RetryNode",
			Handler:    _OrchestratorService_RetryNode_Handler,
		},
		{
			MethodName: "RerunNode",
			Handler:    _OrchestratorService_RerunNode_Handler,
		},
		{
			MethodName: "SkipNode",
			Handler:    _OrchestratorService_SkipNode_Handler,
		},
		{
			MethodName: "TestAgent",
			Handler:    _OrchestratorService_TestAgent_Handler,
		},
		{
			MethodName: "ReloadAgentConfig",
			Handler:    _OrchestratorService_ReloadAgentConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _OrchestratorService_EventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator.proto",
}
